name: Deploy
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false  # 禁用默认凭证缓存
          fetch-depth: 0             # 获取完整历史记录（避免推送冲突）

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy to Master
        run: |
          # 配置 Git 身份
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # 强制添加被忽略的构建产物
          git add -f dist
          
          # 仅当 dist 有变化时才提交
          git diff --cached --quiet || git commit -m "Auto-deploy (built assets)"
          
          # 强制推送到 master 分支
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用自动生成的令牌